/**
 * Enrich topology.json with the synchronous service→service API call graph from
 * the Lansweeper dev-portal catalog.
 *
 * Source: catalog-info.yaml files generated by dev-portal-catalog-files-generator
 * and PR-reviewed by service owners, living in each `*-deployments` repo under
 * `<app>/catalog-info/catalog-info.yaml`. Each Component document exposes
 * providesApis / consumesApis, which reveal the gRPC/HTTP call graph that the
 * Kafka-centric topology does not capture on its own.
 *
 * The enrichment is strictly additive: it only fills the catalog-owned
 * providesApis/consumesApis fields and never touches manually curated data
 * (produces, consumes, databases, grpcCalls, redisPubSub).
 */
import { readFileSync, writeFileSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'
import { execSync } from 'child_process'
import yaml from 'js-yaml'
import type { TopologyData } from '../src/types'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)
const TOPOLOGY_PATH = resolve(__dirname, '../src/data/topology.json')

/** Deployment repositories that call the catalog-files-generator reusable workflow. */
const DEPLOYMENT_REPOS = [
  'analytics-deployments',
  'assetcortex-deployments',
  'audit-deployments',
  'backoffice-deployments',
  'businesstools-deployments',
  'datacore-deployments',
  'dataviz-deployments',
  'devtools-deployments',
  'diagrams-deployments',
  'edge-deployments',
  'enriching-deployments',
  'hivemind-deployments',
  'integrations-deployments',
  'inventory-deployments',
  'lakehouse-deployments',
  'networkobs-deployments',
  'recognition-deployments',
  'reporting-deployments',
  'scanning-deployments',
  'tenancy-deployments',
  'tracking-deployments',
  'webapp-deployments',
]

export interface CatalogDoc {
  kind?: string
  metadata?: { name?: string }
  spec?: {
    owner?: string
    lifecycle?: string
    providesApis?: string[]
    consumesApis?: string[]
    dependsOn?: string[]
    [key: string]: unknown
  }
}

export interface CatalogDiscrepancy {
  service: string
  field: 'owner'
  catalog: string
  topology: string
}

export interface EnrichResult {
  topology: TopologyData
  discrepancies: CatalogDiscrepancy[]
  matched: number
}

/** Parse a multi-document catalog-info.yaml into its non-empty documents. */
export function parseCatalogYaml(text: string): CatalogDoc[] {
  const docs = yaml.loadAll(text) as unknown[]
  return docs.filter((d): d is CatalogDoc => d !== null && typeof d === 'object')
}

const sortedUnique = (values: string[]): string[] => [...new Set(values)].sort()

/**
 * Merge catalog Component data into the topology by joining Component.name to
 * Service.id. Additive only: sets providesApis/consumesApis and collects owner
 * discrepancies without mutating any curated field.
 */
export function enrichWithCatalog(topology: TopologyData, docs: CatalogDoc[]): EnrichResult {
  const discrepancies: CatalogDiscrepancy[] = []
  let matched = 0

  for (const doc of docs) {
    if (doc.kind !== 'Component') continue
    const name = doc.metadata?.name
    if (!name) continue
    const service = topology.services[name]
    if (!service) continue

    matched++

    const provides = doc.spec?.providesApis ?? []
    const consumes = doc.spec?.consumesApis ?? []
    if (provides.length > 0) service.providesApis = sortedUnique(provides)
    if (consumes.length > 0) service.consumesApis = sortedUnique(consumes)

    const owner = doc.spec?.owner
    if (owner && service.team && owner !== service.team) {
      discrepancies.push({ service: name, field: 'owner', catalog: owner, topology: service.team })
    }
  }

  return { topology, discrepancies, matched }
}

/** Fetch every `<app>/catalog-info/catalog-info.yaml` from a deployment repo via gh. */
function fetchRepoCatalogDocs(repo: string): CatalogDoc[] {
  let treeJson: string
  try {
    treeJson = execSync(`gh api "repos/Lansweeper/${repo}/git/trees/HEAD?recursive=1" --jq '.tree[].path'`, {
      encoding: 'utf-8',
      stdio: ['ignore', 'pipe', 'ignore'],
    })
  } catch {
    console.warn(`  ! ${repo}: could not list tree (skipping)`)
    return []
  }

  const paths = treeJson
    .trim()
    .split('\n')
    .filter(p => /catalog-info\/catalog-info\.yaml$/.test(p))

  const docs: CatalogDoc[] = []
  for (const path of paths) {
    try {
      const b64 = execSync(`gh api "repos/Lansweeper/${repo}/contents/${path}" --jq '.content'`, {
        encoding: 'utf-8',
        stdio: ['ignore', 'pipe', 'ignore'],
      })
      const text = Buffer.from(b64, 'base64').toString('utf-8')
      docs.push(...parseCatalogYaml(text))
    } catch {
      console.warn(`  ! ${repo}/${path}: could not read (skipping)`)
    }
  }
  return docs
}

// CLI entrypoint
if (process.argv[1]?.includes('enrich-catalog')) {
  const topology: TopologyData = JSON.parse(readFileSync(TOPOLOGY_PATH, 'utf-8'))

  const allDocs: CatalogDoc[] = []
  for (const repo of DEPLOYMENT_REPOS) {
    const docs = fetchRepoCatalogDocs(repo)
    console.log(`  ${repo}: ${docs.filter(d => d.kind === 'Component').length} components`)
    allDocs.push(...docs)
  }

  const { topology: enriched, discrepancies, matched } = enrichWithCatalog(topology, allDocs)
  writeFileSync(TOPOLOGY_PATH, JSON.stringify(enriched, null, 2))

  const withApis = Object.values(enriched.services).filter(s => s.providesApis || s.consumesApis).length
  console.log(`\nEnriched topology with catalog data:`)
  console.log(`  Matched components: ${matched}`)
  console.log(`  Services with API deps: ${withApis}/${Object.values(enriched.services).length}`)

  if (discrepancies.length > 0) {
    console.log(`\n  Owner discrepancies (catalog vs topology), not auto-applied:`)
    for (const d of discrepancies) {
      console.log(`    ${d.service}: catalog=${d.catalog} topology=${d.topology}`)
    }
  }
}
